using System.Runtime.InteropServices;

namespace IHateDPI.Engine.Native;

/// <summary>
/// Represents the metadata structure containing the packet's timestamp, direction, and layer information.
/// <para>
/// This struct uses <see cref="LayoutKind.Explicit"/> to emulate a C-style Union, 
/// allowing the <see cref="Network"/> and <see cref="Flow"/> fields to share the same memory location.
/// </para>
/// </summary>
[StructLayout(LayoutKind.Explicit)]
public struct WinDivertAddress
{
    /// <summary>
    /// The timestamp of the packet (64-bit).
    /// </summary>
    [FieldOffset(0)]
    public long Timestamp;

    /// <summary>
    /// Bitfield containing layer, direction, and sniffing mode information.
    /// </summary>
    [FieldOffset(8)]
    public uint Flags;

    /// <summary>
    /// Reserved for future use.
    /// </summary>
    [FieldOffset(12)]
    public uint Reserved2;

    /// <summary>
    /// Network layer data (e.g., Interface Index). Valid when Layer is NETWORK.
    /// <para><b>Note:</b> Shares memory offset (16) with <see cref="Flow"/>.</para>
    /// </summary>
    [FieldOffset(16)]
    public WinDivertDataNetwork Network;

    /// <summary>
    /// Flow layer data (e.g., Endpoint ID, Process ID). Valid when Layer is FLOW.
    /// <para><b>Note:</b> Shares memory offset (16) with <see cref="Network"/>.</para>
    /// </summary>
    [FieldOffset(16)]
    public WinDivertDataFlow Flow;

    // --- Helpers ---

    /// <summary>
    /// Gets the layer type from the lowest byte of the flags.
    /// </summary>
    public readonly byte Layer => (byte)(Flags & 0xFF);

    /// <summary>
    /// Gets a value indicating whether the packet is outbound (generated by the local system).
    /// </summary>
    public readonly bool Outbound => ((Flags >> 17) & 1) == 1;

    /// <summary>
    /// Gets a value indicating whether the packet is IPv6.
    /// </summary>
    public readonly bool IPv6 => ((Flags >> 20) & 1) == 1;

    /// <summary>
    /// Sets or clears the outbound flag (Bit 17) for the packet.
    /// </summary>
    /// <param name="isOutbound">Set to <c>true</c> for outbound packets; <c>false</c> for inbound.</param>
    public void SetOutbound(bool isOutbound)
    {
        if (isOutbound)
            Flags |= (1u << 17);
        else
            Flags &= ~(1u << 17);
    }
}

/// <summary>
/// Contains interface information for the Network Layer.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct WinDivertDataNetwork
{
    /// <summary>
    /// The interface index on which the packet was captured or injected.
    /// </summary>
    public uint IfIdx;

    /// <summary>
    /// The sub-interface index.
    /// </summary>
    public uint SubIfIdx;
}

/// <summary>
/// Contains detailed flow and socket information for the Flow Layer.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public struct WinDivertDataFlow
{
    public ulong EndpointId;
    public ulong ParentEndpointId;
    public uint ProcessId;
    public uint LocalAddr0;
    public uint LocalAddr1;
    public uint LocalAddr2;
    public uint LocalAddr3;
    public uint RemoteAddr0;
    public uint RemoteAddr1;
    public uint RemoteAddr2;
    public uint RemoteAddr3;
    public ushort LocalPort;
    public ushort RemotePort;
    public byte Protocol;
}