<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<PackageIcon>app.png</PackageIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>
		<ApplicationIcon>app.ico</ApplicationIcon>
		<AssemblyName>IHateDPI Launcher</AssemblyName>
		<PublishTrimmed>false</PublishTrimmed>
		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
	</PropertyGroup>

	<Target Name="PostBuild" AfterTargets="PostBuildEvent">
		<Exec Command="xcopy /Y /I &quot;$(SolutionDir)src\IHateDPI.Engine\bin\publish\*&quot; &quot;$(TargetDir)Engines\IHateDPI&quot;" />
	</Target>

	<ItemGroup>
	  <Content Include="app.ico">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="WPF-UI" Version="4.1.0" />
	</ItemGroup>

	<ItemGroup>
	  <Resource Include="app.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="app.png">
	    <Pack>True</Pack>
	    <PackagePath>\</PackagePath>
	  </None>
	</ItemGroup>

</Project>
